spring:
  profiles:
    active:
      - dbDev
      - loglocal
      - mongolocal
  jwt:
    secret-key: portpolio
    expire-time: 36000000
    header-key: X-AUTH-TOKEN

spring.main.allow-bean-definition-overriding: true
---
spring:
  profiles: dbDev
  mydb:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/test?&autoReconnect=true&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
        driverClassName: com.mysql.jdbc.Driver
        maximum-pool-size: 20
        #minimum-idle: 100
        max-lifetime: 1800000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none #create 로 해놓으면 Data전체 삭제 됨. 개발 초기에는 update 사용하나 상용에는 none 필수.
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
spring:
  profiles: mongolocal

  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/firestock
---
spring:
  profiles: tomcatlocal

server:
  port: 8080

  tomcat:
    accesslog:
      enabled: true
      prefix: access_log_ladmin-api
      pattern: "[%A] [%v] [%{yyyy-MM-dd HH:mm:ss}t]  [%a] [%h] [%S] [accesslog] [%m] [%r] [%{User-Agent}i]"
    basedir: /Users/kimjimin/logs


